In [1]:
import numpy as np
v1=np.array([1,2,3])
v2=np.array([4,5,6])
print(v1)
print(v2)
v1@v2

[1 2 3]
[4 5 6]


np.int64(32)

In [2]:
v1+v2

array([5, 7, 9])

In [3]:
np.linalg.norm(v1,ord=1)
from math import inf

In [4]:
np.linalg.norm(v2,inf)

np.float64(6.0)

In [5]:
v3=np.array([50,-60,-20])
np.linalg.norm(v3,inf)

np.float64(60.0)

In [6]:
v4=np.array([[1],[6],[7]])

In [7]:
v4

array([[1],
       [6],
       [7]])

In [8]:
v5=np.array([[1],[6],[7]])

In [9]:
v4.T@v5

array([[86]])

In [10]:
v1@v2

np.int64(32)

In [11]:
b=np.array([[1],[11]])
A=np.array([[1,-2],[3,-6]])


In [12]:
Ogmented=np.concatenate((A,b),axis=1)

In [13]:
Ogmented

array([[ 1, -2,  1],
       [ 3, -6, 11]])

In [14]:
import sympy as sm

In [15]:
M=sm.Matrix(Ogmented)
M

Matrix([
[1, -2,  1],
[3, -6, 11]])

In [16]:
M.rref()

(Matrix([
 [1, -2, 0],
 [0,  0, 1]]),
 (0, 2))

In [17]:
x,y=sm.symbols('x y')
sm.linsolve(M,(x,y))

EmptySet

In [18]:
eq=x+y

In [19]:
c=np.array([[1,-2,1],[3,-6,3]])
c



array([[ 1, -2,  1],
       [ 3, -6,  3]])

In [20]:
z=sm.Matrix(c)

In [21]:
c[: , :]

array([[ 1, -2,  1],
       [ 3, -6,  3]])

In [22]:
z

Matrix([
[1, -2, 1],
[3, -6, 3]])

In [23]:
n,m=sm.symbols('n m')
z.rref()

(Matrix([
 [1, -2, 1],
 [0,  0, 0]]),
 (0,))

In [24]:
sm.linsolve(z,(n,m))

{(2*m + 1, m)}

In [25]:
w=sm.Matrix([[2,4,-2,2],[4,9,-3,8],[-2,-3,7,10]])

In [26]:
w.rref()

(Matrix([
 [1, 0, 0, -1],
 [0, 1, 0,  2],
 [0, 0, 1,  2]]),
 (0, 1, 2))

In [27]:
sm.linsolve(w)

{(-1, 2, 2)}

In [28]:
v6=np.array([1,2,3])
v6.shape

(3,)

In [29]:
np.linalg.norm(v6,1)

np.float64(6.0)

In [30]:
s=sm.Matrix([[1,2,3],[4,2.5,3.45],[5.6,33,1.2]])

In [31]:
s

Matrix([
[  1,   2,    3],
[  4, 2.5, 3.45],
[5.6,  33,  1.2]])

In [32]:
s[1]

2

In [33]:
s.det()

272.190000000000

In [34]:
s.inv()

Matrix([
[-0.407252287005401,   0.354899151328116, -0.00220434255483302],
[0.0533450898269591, -0.0573129064256585,   0.0314118814063706],
[ 0.433520702450494, -0.0800911128255998,  -0.0202064734193027]])

In [35]:
s.eigenvects()

[(14.8329050112775,
  1,
  [Matrix([
   [0.245659644011339],
   [0.334216143075916],
   [0.909918078187087]])]),
 (-2.36117553805923,
  1,
  [Matrix([
   [-0.789603417962197],
   [0.0415116508271366],
   [ 0.856990797189408]])]),
 (-7.77172947321827,
  1,
  [Matrix([
   [0.381261788253899],
   [0.291144714528533],
   [-1.30887156469857]])])]

In [36]:
l=np.array([[1,2,3],[4,2.5,3.45],[5.6,33,1.2]])

In [37]:
l

array([[ 1.  ,  2.  ,  3.  ],
       [ 4.  ,  2.5 ,  3.45],
       [ 5.6 , 33.  ,  1.2 ]])

In [38]:
l[0 :1 , 1:3 ]

array([[2., 3.]])

In [39]:
type(l)

numpy.ndarray

In [40]:
l.dtype

dtype('float64')

In [41]:
l

array([[ 1.  ,  2.  ,  3.  ],
       [ 4.  ,  2.5 ,  3.45],
       [ 5.6 , 33.  ,  1.2 ]])

In [42]:
l.sum()

np.float64(55.75000000000001)

In [43]:
l1=l.sum(axis=0)
l2=l.sum(axis=1)

In [44]:
l1.shape 
# بسبب ان الناتج بتاع هملية الجمع ملوش دايمنشن هنقولة ال keepdims=True


(3,)

In [45]:
l3=l.sum(axis=0,keepdims=True)
l3

array([[10.6 , 37.5 ,  7.65]])

In [46]:
l3.shape

(1, 3)

In [47]:
l4=l.sum(axis=1,keepdims=True)

In [48]:
l4.shape

(3, 1)

In [49]:
l4

array([[ 6.  ],
       [ 9.95],
       [39.8 ]])

In [50]:
l1

array([10.6 , 37.5 ,  7.65])

In [51]:
l

array([[ 1.  ,  2.  ,  3.  ],
       [ 4.  ,  2.5 ,  3.45],
       [ 5.6 , 33.  ,  1.2 ]])

In [52]:
l[l>2].shape

(6,)

In [53]:
j=np.random.randn(3,4)

In [54]:
j

array([[-0.08219956,  0.00278464, -0.4286077 , -0.02205082],
       [-0.12928345, -1.07816247,  0.11340116,  2.09106209],
       [ 0.27187511,  0.21490813, -0.57712132, -0.79037636]])

عاوزين نجيب ال matrics المعمولها orthogonalization

In [55]:
import numpy as np
v=np.array([[1,2,3,],[1,0,1],[1,1,-1]])

In [56]:
v

array([[ 1,  2,  3],
       [ 1,  0,  1],
       [ 1,  1, -1]])

In [57]:
Q,R=np.linalg.qr(v)

In [58]:
Q

array([[-5.77350269e-01,  7.07106781e-01, -4.08248290e-01],
       [-5.77350269e-01, -7.07106781e-01, -4.08248290e-01],
       [-5.77350269e-01, -2.60475187e-17,  8.16496581e-01]])

In [59]:
R

array([[-1.73205081, -1.73205081, -1.73205081],
       [ 0.        ,  1.41421356,  1.41421356],
       [ 0.        ,  0.        , -2.44948974]])

In [60]:
v2=np.array([[1,1],[0,2]])

v2

In [61]:
v2

array([[1, 1],
       [0, 2]])

In [62]:
eig_Val,eig_vect=np.linalg.eig(v2)

In [63]:
eig_Val

array([1., 2.])

In [64]:
eig_vect

array([[1.        , 0.70710678],
       [0.        , 0.70710678]])

In [65]:
c=eig_vect

In [66]:
d=np.diag(eig_Val)

In [67]:
d

array([[1., 0.],
       [0., 2.]])

In [68]:
c_inv=np.linalg.inv(c)

In [69]:
c_inv

array([[ 1.        , -1.        ],
       [ 0.        ,  1.41421356]])

In [70]:
np.linalg.matrix_power(v2,3)

array([[1, 7],
       [0, 8]])

In [71]:
c@np.linalg.matrix_power(d,3)@c_inv

array([[1., 7.],
       [0., 8.]])